### ISSUE TITLE
Failed Ajax request or invalid JSON returned

### ISSUE THREAD

**Issue by angie713000** [pkp/customHeader#19]
Error every time i want to add a new user
<img width="1280" alt="Screen Shot 2021-02-16 at 2 24 25 PM" src="https://user-images.githubusercontent.com/79014752/108111442-ae66a300-7062-11eb-9356-f37e4dae135c.png">

I've already reinstalled it and its the same 
What can I do

**Comment by asmecher** [comment]
@angie713000, could you post your question to the support forum (https://forum.pkp.sfu.ca)? That's the best place to get general help. Check your PHP error log and include anything relevant there.
