### ISSUE TITLE
Fatal error in PHP 8 when getting request

### ISSUE THREAD

**Issue by NateWr** [pkp/customHeader#20]
```
PHP Fatal error: Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in /var/www/html/plugins/generic/customHeader/CustomHeaderPlugin.inc.php:112
```

See [forum](https://forum.pkp.sfu.ca/t/php-fatal-error-uncaught-error-non-static-method-pkpapplication-getrequest/66753).

**Comment by NateWr** [comment]
@asmecher I committed directly to `stable-3_3_0` and `main`. Should we release a new version?

**Comment by asmecher** [comment]
Thanks, @NateWr, I'll do that.

**Comment by asmecher** [comment]
(Done)

**Comment by luizbgomide** [comment]
I got one of those in the Scielo Report plugin:
`Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in /plugins/reports/scieloSubmissionsReport/ScieloSubmissionsReportPlugin.inc.php:32`

**Comment by asmecher** [comment]
@luizbgomide, you'd have to follow up with SciELO about that, but it's probably a matter of applying the same fix to that codebase as was required here (https://github.com/pkp/customHeader/commit/166298b35dd7d53dad78dd58cad9148bf986479b).

**Comment by luizbgomide** [comment]
@asmecher I did apply the fix, but I just let you know here because I don't know how to warm the responsible for that module about the issue.

**Comment by asmecher** [comment]
@luizbgomide, you could try this contact address: https://github.com/pkp/plugin-gallery/blob/2cc354af02c18b35a86f27a43a02e59112339248/plugins.xml#L7597
