### ISSUE TITLE
Fatal error with (some versions of) PHP8 on CustomHeaderSettingsForm::execute

### ISSUE THREAD

**Issue by asmecher** [pkp/customHeader#21]
See https://forum.pkp.sfu.ca/t/failed-ajax-request-or-invalid-json-returned-occurred-into-fatal-error-when-editing-custom-header-plugin/70654:
> PHP log says: PHP Fatal error: Declaration of CustomHeaderSettingsForm::execute($request, …$functionArgs) must be compatible with Form::execute(…$functionArgs)

**Comment by asmecher** [comment]
If you're encountering this issue, you can resolve it by applying [this patch](https://github.com/pkp/customHeader/commit/bb9df40eaddf9ce8763ae0579ffaac3e46c80d84.diff) in `plugins/generic/customHeader`.

**Comment by marcbria** [comment]
Tested with PHP8.0.20 and is working perfectly.

Why not including this in next LTS?

**Comment by asmecher** [comment]
> Why not including this in next LTS?

It will be: https://github.com/pkp/customHeader/commit/bb9df40eaddf9ce8763ae0579ffaac3e46c80d84
