### ISSUE TITLE
Where can I see the plugin in action? any live demo?

### ISSUE THREAD

**Issue by asifdev124** [pkp/customHeader#25]
@asmecher Where can I see the plugin in action? any live demo? all I mean e.g. if we have standard theme, what this plugins actually adds to?

**Comment by asmecher** [comment]
@asifdev124, could you post your question on our support forum (https://forum.pkp.sfu.ca/)? That's the best place to get general guidance.

**Comment by asifdev124** [comment]
@asmecher ok I though this is a plugin and I need to see how it work, actually this was my question, thanks
