### ISSUE TITLE
Provide support for editorial backend injection as well

### ISSUE THREAD

**Issue by ctgraham** [pkp/customHeader#28]
ctgraham writes:

> We have the Custom Headers Plugin to allow arbitrary javascript/css/meta customization of the public interface, but no parallel for the backend editorial interface.  I have a use-case requesting the ability to load a javascript widget in the editorial interface which I think makes sense, and I think the general principle is broadly applicable.  I'm picturing Pitt ULS creating a maintaining an "Editorial Custom Headers Plugin" in the Plugin Gallery.  Any reasons this has not be done to-date, or any reason why this wouldn't be a good idea?

natewr suggests:

> I suspect a PR for the custom headers plugin might be welcome. Just add a second text field for headers that should be loaded on the editorial backend.

asmecher affirms:

> Yup, that would be a no-fuss solution.

**Comment by ctgraham** [comment]
@asmecher , can I get a review of PRs:

## #29 [3.3]

and

## #30 [main]

**Comment by lpanebr** [comment]
This plugin is the best! Thanks!

Having it also on the backend would be huge.

**Comment by ctgraham** [comment]
@asmecher , PRs are updated for your merge consideration:

## #29 [3.3]

and

## #30 [main]

**Comment by asmecher** [comment]
Both merged, thanks!

**Comment by lpanebr** [comment]
> Both merged, thanks!

Hi @asmecher I've just installed the plugin on a 3.3.0.14 OJS but the settings only show the same Header and Footer content areas.

How to get the updated version?

**Comment by asmecher** [comment]
@lpanebr, what version of the Custom Header plugin do you have installed?

**Comment by lpanebr** [comment]
@asmecher `v1.0.3.1` is the version that showed up when I searched and installed.

![image](https://github.com/pkp/customHeader/assets/129185/51de87e3-281a-44b4-9a57-e2c293a51083)

**Comment by asmecher** [comment]
@lpanebr, it looks like this was committed to the `stable-3_3_0` branch but not released yet. I've added a new release to the plugin gallery.

**Comment by lpanebr** [comment]
thanks, @asmecher ! I confirm that my installation now shows that the plugin can be upgraded!
![image](https://github.com/pkp/customHeader/assets/129185/fbec3873-0717-411e-b94a-00153e08af6c)

I still haven't found how to upgrade it though, but I should eventually. lol

thanks again!!

**Comment by asmecher** [comment]
@lpanebr, great! If you're logged in as a Site Administrator, there should be a button to upgrade the plugin.

**Comment by lpanebr** [comment]
ah, that's it then. If I understand it correctly administrators are like
highlanders, "there can be only one".
So that would be my IT guy who installed the OJS!
Thanks again!
