### ISSUE TITLE
Settings not visible

### ISSUE THREAD

**Issue by bjarman** [pkp/customHeader#34]
After installing this plugin is only listed in the plugin gallery but does not show in the installed plugins. Where can I find the plugin settings so that I can add custom js to a journal?
OJS version I am using: OJS 3.3.0.14
Plugin version: 1.0.4.1

**Comment by asmecher** [comment]
@bjarman, could you post your question in our support forum at https://forum.pkp.sfu.ca? That's the best place to get help. We use github issues for bug tracking once something has been identified as a bug or specified as a new, scheduled feature.
