### ISSUE TITLE
Also customFooter?

### ISSUE THREAD

**Issue by larsvilhuber** [pkp/customHeader#5]
It would make sense to add a CustomFooter option (within the same plugin), or separate plugin. 

Some Javascript is best loaded late, and some Javascript might depend on code that is not yet loaded (e.g., jquery). Thus, adding custom JS very late would make sense.

**Comment by asmecher** [comment]
Footer content could be added using the `Templates::Common::Footer::PageFooter` hook. Although it would kind of make the plugin name a misnomer, I'd be OK with adding a new form field to this plugin for footer content, as your use case makes sense. PRs welcome!

**Comment by jamshidhashimi** [comment]
PR:

[PR#8](https://github.com/asmecher/customHeader/pull/8)

@asmecher please review. Thanks.

**Comment by asmecher** [comment]
Resolved by https://github.com/asmecher/customHeader/pull/8, thanks!
